# -*- coding: utf-8 -*-
"""Untitled8.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/14_JKBHw_pTPvvttbq4YPk_znnpyL-Geu
"""

import pandas as pd
import numpy as np

data=pd.read_excel("/content/iris.xls")

print(data)

from google.colab import drive
drive.mount('/content/drive')

print(data.head())

data.describe()

print(data.columns)

print(data.mean(numeric_only=True))

print(data.isnull().sum())

import matplotlib.pyplot as plt
import seaborn as sns

plt.figure(figsize=(12,6))
sns.histplot(data,kde=True)
plt.title('distribution of features')
plt.show()

plt.figure(figsize=(8,6))
sns.heatmap(data.corr(numeric_only=True),annot=True,cmap='coolwarm', linewidths=0.5)
plt.title('correlation heatmap')
plt.show()

sns.pairplot(data,hue=data.columns[-1])
plt.show()